# istall script
INSTALLDIR='/usr/bin'

install:
	install xml2dot.py $(INSTALLDIR)/xml2dot
love:
	@echo Sorry but I hadn't hardware for this, okay?
	@echo Contact your hardware vendor for the appropriate module.



