# install script
INSTALLDIR='/usr/bin'

install:

	install wikixml2graph.py $(INSTALLDIR)/wikixml2graph
	install sync.py $(INSTALLDIR)/sync_trustlet
	install syncrm.py $(INSTALLDIR)/syncrm_trustlet
	install lsc2.py $(INSTALLDIR)/lsc2
	install dot2c2.py $(INSTALLDIR)/dot2c2
love:
	@echo Sorry but I hadn\'t hardware for this, okay?
	@echo Contact your hardware vendor for the appropriate module.
