# install script
INSTALLDIR='/usr/bin'

install:
	install wikixml2graph.py $(INSTALLDIR)
	install sync.py $(INSTALLDIR)
	install syncrm.py $(INSTALLDIR)
	install lsc2.py $(INSTALLDIR)/lsc2
	install recDeleteSvnFolders.py $(INSTALLDIR)
love:
	@echo Sorry but I hadn\'t hardware for this, okay?
	@echo Contact your hardware vendor for the appropriate module.
