# istall script
INSTALLDIR='/usr/bin'

install:
	install netevolution.py $(INSTALLDIR)/netevolution

love:
	@echo Guarda, non sono equipaggiato per questo, okay?
	@echo Contatta il rivenditore del tuo hardware per i moduli appropriati.


